- name: Create MQ backup directory
  ansible.builtin.file:
    path: "{{ mq_backup_dir }}"
    state: directory
    mode: '0777'

- name: Back up existing Queue Manager data
  ansible.builtin.shell:
    cmd: "su mqm -c 'dmpmqcfg -x all -t all -o mqsc -m {{ mq_manager_name }} > {{ mq_backup_dir }}{{ mq_manager_name }}.mqsc'"

- name: Back up existing Queue Manager data auth.txt
  ansible.builtin.shell:
    cmd: "su mqm -c 'dmpmqcfg -x all -t all -o setmqaut -m {{ mq_manager_name }} >> {{ mq_backup_dir }}{{ mq_manager_name }}_auth.txt'"

- name: Copy qm.ini
  ansible.builtin.copy:
    src: "{{ mq_qm_data_src }}"
    dest: "{{ mq_backup_dir }}"
    remote_src: yes

- name: Fetch files
  fetch:
    src: "{{ mq_backup_dir }}{{ item }}"
    dest: "{{ ansible_copy_path }}"
    flat: yes
  loop: "{{ mq_backup_files }}"
